#!/usr/bin/env sh
##############################################################################
##  Gradle start up script for POSIX generated by OpenAI helper.
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"
GRADLE_WRAPPER_JAR="$DIR/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
  echo "Missing gradle wrapper jar: $GRADLE_WRAPPER_JAR"
  echo "Open this project in Android Studio; it will recreate wrapper files if needed."
  exit 1
fi

JAVA_CMD="java"
exec "$JAVA_CMD" -classpath "$GRADLE_WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
